CREATE TABLE `indicateur_darwin_extract_brut` (
  `ID` int(20) NOT NULL auto_increment,
  `Demande` varchar(20) NOT NULL,
  `Cle` varchar(20) NOT NULL,
  `Resume` varchar(200) NOT NULL,
  `Type` varchar(20) NOT NULL,
  `Etat` varchar(20) NOT NULL,
  `Motif` varchar(20) NOT NULL,
  `Intervenant` varchar(50) NOT NULL,
  `Demandeur` varchar(50) NOT NULL,
  `Creation` varchar(20) NOT NULL,
  `Mise a jour` varchar(20) NOT NULL,
  `Resolue` varchar(20) NOT NULL,
  `Composants` varchar(20) default NULL,
  `Date souhaitee 1` varchar(20) default NULL,
  `Observateurs` int(6) NOT NULL,
  `Images` varchar(200) default NULL,
  `Estimation originale` varchar(20) default NULL,
  `Estimation restante` varchar(20) default NULL,
  `Temps consacre` varchar(20) default NULL,
  `Ratio du travail reel compare a estimation` varchar(20) default NULL,
  `Sous-taches` varchar(20) default NULL,
  `Demandes liees` varchar(20) default NULL,
  `Descriptif` varchar(500) NOT NULL,
  `Niveau de securite` varchar(20) default NULL,
  `Progression` varchar(20) default NULL,
  `S Progres` varchar(20) default NULL,
  `S Temps consacre` varchar(20) default NULL,
  `S Estimation restante` varchar(20) default NULL,
  `S Estimation originale` varchar(20) default NULL,
  `Libelle` varchar(200) NOT NULL,
  `Code Convention` varchar(20) default NULL,
  `Code application` varchar(5) NOT NULL,
  `Composant` varchar(200) NOT NULL,
  `Date souhaitee 2` varchar(50) NOT NULL,
  `Entite metier` varchar(20) NOT NULL,
  `Env. physique` varchar(20) default NULL,
  `Environnement` varchar(20) NOT NULL,
  `ID application` int(5) NOT NULL,
  `Facturation` varchar(200) NOT NULL,
  `Annulation` varchar(50) NOT NULL,
  `Resolution` varchar(50) NOT NULL,
  `Niveau d expertise` varchar(20) NOT NULL,
  `Niveau de service` varchar(20) NOT NULL,
  `PercentDone` varchar(20) default NULL,
  `Refacturation` varchar(200) NOT NULL,
  `RefIncidentclient` varchar(20) default NULL,
  `Site` varchar(10) NOT NULL,
  `TempsJours` int(3)   default NULL,
  `TempsHeure` int(3)   default NULL,
  `TempsMinutes` int(5)   default NULL,
  `ENABLE` int(1) NOT NULL,
  PRIMARY KEY  (`ID`),
  KEY `ENABLE` (`ENABLE`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1